### PR TITLE
Insert relative path for org

### PR DESCRIPTION
**Pull request by waynezhang**
Just made a simple fix for relative path of file link at https://github.com/ihdavids/orgextended/commit/bc64d2b90e7628977677c6dbaa141b7e5bdf378c.
And cannot help myself making some code style cleanup for `orglinks.py`.

### CODE REVIEW

**Review by ihdavids — CHANGES_REQUESTED** [review]
Please, no code formatting changes like this.
I wont maintain them and they tend to just make merging more challenging as more people work on the source base.

**Comment by waynezhang** [comment]
Reverted the last commit.

**Review by ihdavids — APPROVED** [review]
Thanks.
The import cleanup was great, just the mass code formatting is problematic for me. 

No problem if you do that in a localized fashion on the code you are working on though.

Mass formatters are something I find distasteful for various reasons.

**Comment by ihdavids** [comment]
I added the relative path stuff to the tooltip / autocomplete version of the insert as well.
Also settings: 
"linkFindUseRoamTags": false

In your settings file will turn off the roam tags if you don't want them.  Honestly they are of less utility since you can't search them like you can with ivy in emacs.

**Comment by ihdavids** [comment]
I also reapplied your import cleanup. That was very good to keep, just the blanket auto formatting was what I was hoping we could avoid.

**Comment by waynezhang** [comment]
Totally get that. I had vim set with linter which complains a lot that makes codes a little hard to read. So I made this change. I'll keep that in mind.

**Pull request merged**
