### PR TITLE
Add option to strip tag from file link

### PR DESCRIPTION
**Pull request by waynezhang**
Added an option for inserting roam tag to file link.

### CODE REVIEW

**Review by ihdavids — APPROVED** [review]
You will need to merge with my changes but this is looking good.

**Comment by ihdavids** [comment]
Heh, guess I should have read your original comment better. I interpreted your comment to read that you didn't like the tags appearing in the description in the quick panel not in the link. :) 

So I made it possible just to turn them off globally. Both options have utility though, so might as well just keep both.

**Comment by waynezhang** [comment]
Yeah. I totally agree with you that tags should be searchable. I just don't like the tag appears in the link. I'll resolve the conflict.

**Review by ihdavids — APPROVED** [review]
Looks great.
This is awesome. Thank you for putting up with me.

**Pull request merged**
